### ISSUE TITLE
Add link to Wikipedia, if answer based on its article

### ISSUE THREAD

**Issue by gomzyakov** [askwiki/wikipedia-dump-splitter#4]

**Comment by galchenok** [comment]
Не стоит добавлять ссылку на Википедию к каждой статье, т.к. этого не требует лицензия Википеции, а сама статья не будет нести какой-то дополнительной информации (она итак уже разбита на вопросы).

**Comment by galchenok** [comment]
Можно добавить ссылки на смежные вопросы из вики-статьи, но это надо думать.

Достаточно будет того, что вопросы будут иметь общую категорию.

**Comment by gomzyakov** [comment]
Согласен
